export const houseRental = [
  {
    price: 2000,
    city: "Manhatan",
    address: "210, Wayne Mansion",
    country: "USA",
    amenities: [
      "Swimming Pool",
      "PlayGround",
      "terrace",
      "Basket Ball",
      "Squash",
      "Golf Course",
      "Home Theater",
      "Bowling",
      "gaming room",
      "gym",
    ],
    size: "2bhk",
    bedrooms: 2,
    bathroom: 3,
    image: "./images/house1.jpg",
  },
  {
    price: 650,
    city: "New York",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: [
      "Swimming Pool",
      "Squash",
      "Golf Course",
      "Home Theater",
      "Bowling",
      "gaming room",
      "gym",
    ],
    size: "2bhk",
    bedrooms: 6,
    bathroom: 10,
    image: "./images/house2.jpg",
  },
  {
    price: 2000,
    city: "Basil",
    address: "Chumantar Gali",
    country: "France",
    amenities: [
      "Swimming Pool",
      "PlayGround",
      "terrace",
      "Bowling",
      "gaming room",
      "gym",
    ],
    size: "3bhk",
    bedrooms: 3,
    bathroom: 1,
    image: "./images/house3.jpg",
  },
  {
    price: 970,
    city: "Beijing",
    address: "0991, Stark Tower",
    country: "China",
    amenities: [
      "Swimming Pool",
      "Golf Course",
      "Home Theater",
      "Bowling",
      "gaming room",
      "gym",
    ],
    size: "1bhk",
    bedrooms: 1,
    bathroom: 1,
    image: "./images/house4.jpg",
  },
  {
    price: 650,
    city: "Delhi",
    address: "0991, Stark Tower",
    country: "India",
    amenities: [
      "Swimming Pool",
      "PlayGround",
      "terrace",
      "Basket Ball",
      "Squash",
      "Golf Course",
      "gym",
    ],
    size: "4bhk",
    bedrooms: 4,
    bathroom: 2,
    image: "./images/house5.jpg",
  },
  {
    price: 150,
    city: "Ranikhet",
    address: "0991, Stark Tower",
    country: "India",
    amenities: ["Golf Course", "Home Theater", "Bowling", "gaming room", "gym"],
    size: "6bhk",
    bedrooms: 6,
    bathroom: 7,
    image: "./images/house6.jpg",
  },
  {
    price: 1050,
    city: "Mhow",
    address: "210, Wayne Mansion",
    country: "India",
    amenities: ["Swimming Pool", "gaming room", "gym"],
    size: "3bhk",
    bedrooms: 3,
    bathroom: 2,
    image: "./images/house7.jpg",
  },
  {
    price: 780,
    city: "Moscow",
    address: "0991, Stark Tower",
    country: "Russia",
    amenities: ["Swimming Pool", "PlayGround", "terrace", "gaming room", "gym"],
    size: "4bhk",
    bedrooms: 4,
    bathroom: 2,
    image: "./images/house8.jpg",
  },
  {
    price: 2330,
    city: "Tokyo",
    address: "0991, Stark Tower",
    country: "Japan",
    amenities: ["gym"],
    size: "3bhk",
    bedrooms: 3,
    bathroom: 1,
    image: "./images/house9.jpg",
  },
  {
    price: 1950,
    city: "Kyoto",
    address: "210, Wayne Mansion",
    country: "Japan",
    amenities: ["Swimming Pool", "PlayGround", "Bowling", "gaming room", "gym"],
    size: "7bhk",
    bedrooms: 7,
    bathroom: 9,
    image: "./images/house10.jpg",
  },
  {
    price: 1750,
    city: "Konoha",
    address: "0991, Stark Tower",
    country: "Village Hidden in Fire",
    amenities: [
      "PlayGround",
      "terrace",
      "Basket Ball",
      "Squash",
      "Golf Course",
      "gym",
    ],
    size: "1bhk",
    bedrooms: 1,
    bathroom: 1,
    image: "./images/house11.jpg",
  },

  {
    price: 7250,
    city: "Sydney",
    address: "0991, Stark Tower",
    country: "Australia",
    amenities: ["Swimming Pool", "gaming room", "gym"],
    size: "2bhk",
    bedrooms: 2,
    bathroom: 1,
    image: "./images/house12.jpg",
  },
  {
    price: 1050,
    city: "Budapest",
    address: "210, Wayne Mansion",
    country: "Hungary",
    amenities: ["Swimming Pool", "terrace", "gym"],
    size: "5bhk",
    bedrooms: 5,
    bathroom: 3,
    image: "./images/house13.jpg",
  },
  {
    price: 659,
    city: "New York",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["gym"],
    size: "5bhk",
    bedrooms: 5,
    bathroom: 3,
    image: "./images/house2.jpg",
  },
  {
    price: 2000,
    city: "New York",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Swimming Pool", "Bowling", "gaming room", "gym"],
    size: "8bhk",
    bedrooms: 8,
    bathroom: 7,
    image: "./images/house1.jpg",
  },
  {
    price: 650,
    city: "New York",
    address: "210, Wayne Mansion",
    country: "USA",
    amenities: [
      "Swimming Pool",
      "PlayGround",
      "terrace",
      "Basket Ball",
      "Squash",
    ],
    size: "2bhk",
    bedrooms: 2,
    bathroom: 1,
    image: "./images/house3.jpg",
  },
  {
    price: 234,
    city: "New York",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Swimming Pool", "gym"],
    size: "4bhk",
    bedrooms: 4,
    bathroom: 4,
    image: "./images/house4.jpg",
  },
  {
    price: 523,
    city: "Tokyo",
    address: "210, Wayne Mansion",
    country: "USA",
    amenities: ["Home Theater", "Bowling"],
    size: "6bhk",
    bedrooms: 6,
    bathroom: 3,
    image: "./images/house5.jpg",
  },
  {
    price: 7524,
    city: "New York",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Swimming Pool", "Golf Course", "gym"],
    size: "4bhk",
    bedrooms: 4,
    bathroom: 3,
    image: "./images/house6.jpg",
  },
  {
    price: 5435,
    city: "Mumbai",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Golf Course", "Home Theater"],
    size: "5bhk",
    bedrooms: 5,
    bathroom: 2,
    image: "./images/house7.jpg",
  },
  {
    price: 6103,
    city: "Paris",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Golf Course", "Home Theater", "Bowling"],
    size: "7bhk",
    bedrooms: 7,
    bathroom: 7,
    image: "./images/house8.jpg",
  },
  {
    price: 812,
    city: "New York",
    address: "210, Wayne Mansion",
    country: "USA",
    amenities: ["Swimming Pool", "PlayGround", "terrace"],
    size: "3bhk",
    bedrooms: 3,
    bathroom: 1,
    image: "./images/house9.jpg",
  },
  {
    price: 620,
    city: "Konoha",
    address: "Chumantar Gali",
    country: "USA",
    amenities: ["Swimming Pool", "Squash", "Bowling", "gaming room", "gym"],
    size: "2bhk",
    bedrooms: 2,
    bathroom: 1,
    image: "./images/house10.jpg",
  },
  {
    price: 923,
    city: "Tokyo",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Basket Ball", "Squash", "Bowling", "gaming room", "gym"],
    size: "3bhk",
    bedrooms: 3,
    bathroom: 1,
    image: "./images/house12.jpg",
  },
  {
    price: 146,
    city: "Mhow",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Swimming Pool", "Bowling"],
    size: "3bhk",
    bedrooms: 3,
    bathroom: 2,
    image: "./images/house11.jpg",
  },
  {
    price: 953,
    city: "Moscow",
    address: "210, Wayne Mansion",
    country: "USA",
    amenities: ["PlayGround", "terrace", "gym"],
    size: "5bhk",
    bedrooms: 5,
    bathroom: 3,
    image: "./images/house13.jpg",
  },
  {
    price: 9345,
    city: "Moscow",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Swimming Pool"],
    size: "2bhk",
    bedrooms: 2,
    bathroom: 1,
    image: "./images/house2.jpg",
  },
  {
    price: 893,
    city: "Rio",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: ["Swimming Pool", "gym"],
    size: "5bhk",
    bedrooms: 5,
    bathroom: 2,
    image: "./images/house1.jpg",
  },
  {
    price: 930,
    city: "Rio",
    address: "0991, Stark Tower",
    country: "USA",
    amenities: [
      "Swimming Pool",
      "PlayGround",
      "terrace",
      "Basket Ball",
      "Squash",
    ],
    size: "7bhk",
    bedrooms: 7,
    bathroom: 4,
    image: "./images/house6.jpg",
  },
  {
    price: 724,
    city: "Mhow",
    address: "210, Wayne Mansion",
    country: "USA",
    amenities: ["Home Theater", "Bowling", "gaming room", "gym"],
    size: "2bhk",
    bedrooms: 2,
    bathroom: 1,
    image: "./images/house8.jpg",
  },
];

export let city = [];
export let ameneties = [];
export let price = [];
export let size = [];

for (let i = 0; i < houseRental.length; i++) {
  //adding unique cities
  if (!city.includes(houseRental[i].city)) {
    city.push(houseRental[i].city);
  }

  //adding unique amenities
  let uniqueAmenities = [...houseRental[i].amenities];
  for (let j = 0; j < uniqueAmenities.length; j++) {
    if (!ameneties.includes(uniqueAmenities[j])) {
      ameneties.push(uniqueAmenities[j]);
    }
  }

  //adding unique prices
  if (!price.includes(houseRental[i].price)) {
    price.push(houseRental[i].price);
  }

  //adding unique size
  if (!size.includes(houseRental[i].size)) {
    size.push(houseRental[i].size);
  }
}

export let priceOpt = [
  "$1 - $499",
  "$500 - $999",
  "$1000 - $1999",
  "$2000 - $4999",
  "$5000 - $9999",
  "$10000 - $14999",
  "$15000 - $24999",
  "$25000 - $49999",
];
